### ISSUE TITLE
关于yelp数据疑惑

### ISSUE THREAD

**Issue by CreaterLL** [JarenceSJ/ReviewGraph#1]
您好，读了您的文章，感觉非常受启发，但在我尝试复现结果时，对于yelp数据集有疑问：
①文章中yelp数据集指向的链接，我无法确定需要下载哪几个文件。
②word2vector.py中第48行dataset_path = '/home/d1/shuaijie/data/yelp-recsys-2013/yelp2013.json' 所示得数据形式 并没有在问题①中所指向的链接中出现，请问是如何得来的呢？
谢谢！

**Comment by JarenceSJ** [comment]
多谢关注，目前放出来的版本还未整理完毕。 word2vector.py 不是文章提出图模型的必要执行步骤，因为历史遗留导致可能需要该代码预处理数据，后续会尽快整理代码并更新。 yelp2013.json 是我经过预处理成和 amazon review 一样的 5-core形式， 这里是[yelp 预处理代码](https://github.com/JarenceSJ/ReviewGraph/blob/db47d342825e7ee3b5eafedfffcae60c726d531d/load_data.py#L444)。

**Comment by CreaterLL** [comment]
明白了，谢谢您！

**Comment by ryy980622** [comment]
请问load_yelp2013(dataset_path)函数中的dataset_path是什么呢？您可以直接将预处理好的yelp2013.json也放出来嘛？
