### ISSUE TITLE
关于yelp数据集和CDs_and_Vinyl_5数据集的处理

### ISSUE THREAD

**Issue by ShijcSJTU** [JarenceSJ/ReviewGraph#4]
作者您好！您的文章给了我很大的启发，我正在学习您的工作。在复现过程中我遇到了以下问题：
我使用Data prepration的三个步骤顺利处理了Digital_Music_5、Digital_Music_5、Clothing这三个数据集，但是在处理数据量较大的CDs_and_Vinyl_5时，在运行第三步bert_whitening.py时每次都被中途killed，把batch size改小也没有用，请问可以从哪些方面排查问题呢。非常感谢！
期待您的回复与指教！

**Comment by JarenceSJ** [comment]
这个和 batch_size 没有关系。whitening 操作可以分批运算。具体可以参考苏神的[博客](https://kexue.fm/archives/8069)
